# Generated by Django 2.2.6 on 2021-09-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=256)),
                ('filename', models.CharField(max_length=256)),
                ('assignment_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('activity_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('content', models.TextField(blank=True, null=True)),
                ('id_number', models.CharField(max_length=16)),
                ('time_limit', models.IntegerField(default=2)),
                ('memory_limit', models.IntegerField(default=256)),
                ('attempt_number', models.IntegerField()),
                ('due_date', models.IntegerField()),
                ('cut_off_date', models.IntegerField()),
                ('time_modified', models.IntegerField()),
                ('grade', models.IntegerField(default=0)),
                ('verdict', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[
                 ('P', 'Pending'), ('G', 'Grading'), ('E', 'Error'), ('D', 'Done')], default='P', max_length=2)),
            ],
            options={
                'ordering': ['-time_modified'],
            },
        ),
    ]
