# Generated by Django 2.2.6 on 2020-10-02 12:08

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('problem_name', models.CharField(max_length=256)),
                ('filename', models.CharField(max_length=256)),
                ('assignment_id', models.IntegerField(db_index=True)),
                ('course_id', models.IntegerField()),
                ('activity_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('content', models.TextField()),
                ('id_number', models.CharField(max_length=16)),
                ('time_limit', models.IntegerField(default=2)),
                ('memory_limit', models.IntegerField(default=256)),
                ('attempt_number', models.IntegerField()),
                ('due_date', models.IntegerField()),
                ('cut_off_date', models.IntegerField()),
                ('time_modified', models.IntegerField(db_index=True)),
                ('grade', models.IntegerField(default=0)),
                ('verdict', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('G', 'Grading'), ('E', 'Error'), ('D', 'Done')], default='P', max_length=2)),
            ],
            options={
                'ordering': ['-time_modified'],
            },
        ),
    ]
