# Generated by Django 2.2.10 on 2020-03-07 14:08

from django.db import migrations, models, connection


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_delete_submission'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Submission',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('problem_name', models.CharField(max_length=256)),
                        ('filename', models.CharField(max_length=256)),
                        ('assignment_id', models.IntegerField()),
                        ('user_id', models.IntegerField()),
                        ('content', models.TextField()),
                        ('id_number', models.CharField(max_length=16)),
                        ('time_limit', models.IntegerField(default=2)),
                        ('memory_limit', models.IntegerField(default=256)),
                        ('attempt_number', models.IntegerField()),
                        ('due_date', models.IntegerField()),
                        ('cut_off_date', models.IntegerField()),
                        ('time_modified', models.IntegerField()),
                        ('grade', models.IntegerField(default=0)),
                        ('status', models.CharField(choices=[
                         ('P', 'Pending'), ('G', 'Grading'), ('D', 'Done')], default='P', max_length=2)),
                    ],
                    options={
                        'ordering': ['-time_modified'],
                    },
                ),
            ]
        )
    ]
