# Generated by Django 2.2.6 on 2021-09-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0002_auto_20210922_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Compiling'), ('G', 'Grading'), ('E', 'Error'), ('D', 'Done')], default='P', max_length=2),
        ),
    ]
