version: "3.7"

services:
  web:
    build:
      context: .
      args:
        HTTP_PROXY: ${HTTP_PROXY}
    image: grader-base
    restart: always
    depends_on:
      - redis
      - mysql
    env_file: .env
    ports:
      - 18080:8080
    volumes:
      - ${DJANGO_MEDIA_LOCATION}:/graderng/media

  worker:
    image: grader-base
    restart: always
    depends_on:
      - redis
      - mysql
    command: ["worker"]
    env_file: .env
    privileged: true
    tmpfs:
      - /tmp-grader
    volumes:
      - ${DJANGO_MEDIA_LOCATION}:/graderng/media

  testcases:
    image: grader-base
    restart: always
    depends_on:
      - redis
    command: ["testcases"]
    env_file: .env
    privileged: true
    tmpfs:
      - /tmp-grader

  redis:
    image: redis:5.0.6
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - 16379:6379

  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DBNAME}
    volumes:
      - ${MYSQL_DATA_LOCATION}:/var/lib/mysql
    restart: always
