version: "3.7"

services:
  web:
    build:
      context: .
      args:
        HTTP_PROXY: ${HTTP_PROXY}
    image: grader-base
    restart: always
    depends_on:
      - redis
      - mongo
    env_file: .env
    ports:
      - 18080:8080
    volumes:
      - ${DJANGO_MEDIA_LOCATION}:/graderng/media

  worker:
    image: grader-base
    restart: always
    depends_on:
      - redis
      - mongo
    command: ["worker"]
    env_file: .env
    privileged: true
    tmpfs:
      - /tmp-grader
    volumes:
      - ${DJANGO_MEDIA_LOCATION}:/graderng/media

  feedbacks_jobs:
    image: grader-base
    restart: always
    depends_on:
      - redis
      - mongo
    command: ["feedbacks_jobs"]
    env_file: .env
    volumes:
      - ${DJANGO_MEDIA_LOCATION}:/graderng/media

  testcases:
    image: grader-base
    restart: always
    depends_on:
      - redis
    command: ["testcases"]
    env_file: .env
    privileged: true
    tmpfs:
      - /tmp-grader

  redis:
    image: redis:5.0.6
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    ports:
      - 16379:6379

  mongo:
    image: mongo:4.2.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DBNAME}
    volumes:
      - ${MONGO_DATA_LOCATION}:/data/db
    restart: always
