version: "3.7"
services:
  web:
    build:
      context: .
      args:
        HTTP_PROXY: ${HTTP_PROXY}
    restart: always
    depends_on:
      - redis
      - mongo
    env_file: .env
    ports:
      - 18080:18080
    privileged: true
    volumes:
      - ${DJANGO_MEDIA_LOCATION}:/graderng/media

  worker:
    build:
      context: .
      args:
        HTTP_PROXY: ${HTTP_PROXY}
    restart: always
    depends_on:
      - redis
      - mongo
      - web
    command: ["worker"]
    env_file: .env
    privileged: true
    volumes:
      - ${DJANGO_MEDIA_LOCATION}:/graderng/media

  feedbacks_jobs:
    build:
      context: .
      args:
        HTTP_PROXY: ${HTTP_PROXY}
    restart: always
    depends_on:
      - redis
      - mongo
      - web
    command: ["feedbacks_jobs"]
    env_file: .env
    volumes:
      - ${DJANGO_MEDIA_LOCATION}:/graderng/media

  redis:
    image: redis:5.0.6
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always

  mongo:
    image: mongo:4.2.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DBNAME}
    volumes:
      - ${MONGO_DATA_LOCATION}:/data/db
    restart: always
