deploy:
  image: alpine:3.10.2
  stage: deploy
  only:
    refs:
      - master
    changes:
      - graderng/**/*
  script:
    - apk add --no-cache openssh
    - echo -e $SSH_KEY > KEY
    - chmod 600 KEY
    - ssh -q -oStrictHostKeyChecking=no $SSH_USERNAME@$SOFITA_IP -i KEY "
        cd $SOFITA_PATH
        && git stash
        && git checkout master
        && git pull origin master        
        && bash deploy.sh
      "
