# Generated by Django 2.2.6 on 2020-03-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MossJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.IntegerField()),
                ('time_created', models.DateTimeField()),
                ('template', models.TextField(blank=True)),
                ('log', models.TextField()),
                ('zip_file', models.FileField(upload_to='moss/')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Running'), ('F', 'Failed'), ('D', 'Done')], default='P', max_length=2)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
    ]
