# Generated by Django 2.2.6 on 2019-11-01 10:25

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('problem_name', models.CharField(max_length=255)),
                ('assignment_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('content', models.TextField()),
                ('id_number', models.CharField(max_length=15)),
                ('time_limit', models.IntegerField(default=3)),
                ('memory_limit', models.IntegerField(default=256)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=app.models.generate_token, max_length=63)),
            ],
        ),
    ]
