# Generated by Django 2.2.10 on 2020-03-07 12:54

from django.db import migrations, connection


def forwards_submission(apps, _):
    """
    Submission is moved, need to migrate schema to the new one
    """

    with connection.cursor() as cursor:
        sql = 'UPDATE "__schema__" SET "name" = %s WHERE "__schema__"."name" = %s'
        cursor.execute(sql, params=["grader_submission", "app_submission"])


def reverse_submission(apps, _):
    """
    Submission is moved, need to migrate schema to the old one
    """

    with connection.cursor() as cursor:
        sql = 'UPDATE "__schema__" SET "name" = %s WHERE "__schema__"."name" = %s'
        cursor.execute(sql, params=["app_submission", "grader_submission"])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable('Submission', 'grader_submission'),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='Submission',
                ),
            ],
        ),
        migrations.RunPython(forwards_submission, reverse_submission),
    ]
