# Generated by Django 2.2.6 on 2020-10-02 11:40

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MossJob',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('assignment_id', models.IntegerField()),
                ('time_created', models.DateTimeField(db_index=True)),
                ('template', models.TextField(blank=True)),
                ('log', models.TextField()),
                ('zip_file', models.FileField(upload_to='moss/')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Running'), ('F', 'Failed'), ('D', 'Done')], default='P', max_length=2)),
                ('name', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('assignment_id', models.IntegerField()),
                ('time_created', models.DateTimeField(db_index=True)),
                ('log', models.TextField()),
                ('csv_file', models.FileField(upload_to='reports/')),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Running'), ('F', 'Failed'), ('D', 'Done')], default='P', max_length=2)),
                ('name', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'ordering': ['-time_created'],
            },
        ),
    ]
