# Generated by Django 2.2.6 on 2021-09-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20210922_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mossjob',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mossjob',
            name='time_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportjob',
            name='time_created',
            field=models.DateTimeField(null=True),
        ),
    ]
