# Generated by Django 2.2.6 on 2021-09-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20210924_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mossjob',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reportjob',
            options={},
        ),
    ]
